### ISSUE TITLE
No write.jplace function? 

### ISSUE THREAD

**Issue by adriaaula** [GuangchuangYu/treeio#112]
Hi! 

I was interested into reading a `jplace` file, perform some modifications and then saving it again. But I have found that the `write.jplace` function is not there.

In the chapter it appears as It should be present: 

> To facilitate storing the merged data into a single file, treeio implemented write.jplace function to export tree object to a jplace file that has a robust format for storing complex data associated with the phylogenetic tree. The jplace file can be parsed and imported into R by our read.jplace function for future use.

[https://guangchuangyu.github.io/ggtree-book/chapter-treeio.html](https://guangchuangyu.github.io/ggtree-book/chapter-treeio.html)

I have checked the code in the github project and it doesn't seem to be a function for that. There is `write.jtree` but  I want to preserve all the initial information contained in the tree, and `jtree` doesn't do that. 

I am using `treeio_1.18.1`. 

Thanks a ton!

**Comment by GuangchuangYu** [comment]
pls use the `github` version of `treeio`.
