### ISSUE TITLE
tree_subset function no longer exists in the recent release of treeio

### ISSUE THREAD

**Issue by NPSDC** [GuangchuangYu/treeio#125]
I recently updated R and accordingly treeio, and I no longer see `tree_subset` function being exported by the package. Is there a reason why it is not there? I could also not find the function in the R source files in the repository (it existed in the previous versions).

**Comment by aidaanva** [comment]
I have encountered the same, and I was wondering as well about the reason why it was not including

**Comment by nearinj** [comment]
I have also ran into this issue and it has broke a tool that is currently in development.

**Comment by xiangpin** [comment]
The `tree_subset` has been moved to `tidytree` package.
