### ISSUE TITLE
Reading raxml-ng trees with bootstrap support

### ISSUE THREAD

**Issue by ksw9** [GuangchuangYu/treeio#20]
Hi and many thanks for a great package, 

I'm trying to plot RAxML-ng trees with bootstrap support values. The function read.raxml, which works well with trees fit with earlier versions of RAxML, does not seem to work with RAxML-ng trees with bootstrap support and results in error, as below: 
```
t <- read.raxml(file = "trees/test_snps_JC.raxml.support")
Error in eval_tidy(xs[[i]], unique_output) : object 'bootstrap' not found
```
I'm attaching my tree file, fit with RaxML-ng. 
[test.raxml.support.txt](https://github.com/GuangchuangYu/treeio/files/3437442/test.raxml.support.txt)

I'm wondering if you would be able to suggest a work-around or if there is another tool that I could use? 

Thank you in advance!

**Comment by brj1** [comment]
You can the `read.tree` function in the ape library (or ggtree library) to read these tree files. The bootstrap support values are stored in the node labels.

```R
library(ggtree)

t <- read.tree(file = "trees/test_snps_JC.raxml.support")

# to plot tree with bootstrap values
ggtree(t) + geom_nodelab(aes(label=label))

# to plot tree with bootstrap values above 90%
ggtree(t) + geom_nodelab(aes(label=label), subset=as.numeric(label) > 90))
```

**Comment by brj1** [comment]
You can access the bootstrap support values via `t$node.label`

**Comment by GuangchuangYu** [comment]
you can also use `read.newick` with `node.label = 'support'`.

e.g. `read.newick(file, node.label='support')`

**Comment by ksw9** [comment]
Thanks both, and sorry for not realizing this earlier!
Thanks for a great package.
All the best,
