### ISSUE TITLE
Ntip issue

### ISSUE THREAD

**Issue by cmunro** [GuangchuangYu/treeio#3]
https://github.com/GuangchuangYu/treeio/blob/1b04db0b855870ab671077a705f99d98eeaa1701/R/method-drop-tip.R#L36

I had the following error running droptip on a treedata object:

> Error inUseMethod("Ntip") :  no applicable method for 'Ntip' applied to an object of class "treedata"

I believe this line should be: 
`object@phylo$node.label <- Ntip(object@phylo) + (1:Nnode(object@phylo))`

Likewise on line 47

**Comment by GuangchuangYu** [comment]
```
detach(package:ape)
```

should works.

Will change the Ntip function to S3 methods by importing ape:Ntip generics in future release.

**Comment by GuangchuangYu** [comment]
done in devel branch.
