### ISSUE TITLE
Please make a new release on BioC

### ISSUE THREAD

**Issue by andersgs** [GuangchuangYu/treeio#6]
Hi @GuangchuangYu. Thank you for `ggtree` and `treeio`. My package `harrietr` depends on `ggtree`, and I am trying to push an update to CRAN, but my checks are ERRORing out because:

`Error : object 'read.fasta' is not exported by 'namespace:treeio'`

Indeed, that seems to be the case for version `1.2.1`, but from my reading of the current code, it has been fixed in the latest version on GitHub. 

Anyway, I would be very thankful if you could make a new release of `treeio` on BC.

Thanks again.

Anders.

**Comment by GuangchuangYu** [comment]
see <https://www.bioconductor.org/developers/release-schedule/>.

**Comment by andersgs** [comment]
Thank you, @GuangchuangYu. I did not realise bioc was on a single release schedule. I'll talk to the CRAN folks and see what can be done.
